### ISSUE TITLE
[ERROR] TypeError: Cannot set property 'callback' of undefined at Object.normalizeQueryConfig 

### ISSUE THREAD

**Issue by olalonde** [kunklejr/node-db-migrate#105]
```
      [ERROR] TypeError: Cannot set property 'callback' of undefined
           at Object.normalizeQueryConfig (/tmp/build_n5qhc5pi52o4/node_modules/pg/lib/utils.js:96:23)
           at new Query (/tmp/build_n5qhc5pi52o4/node_modules/pg/lib/query.js:12:18)
           at Client.query (/tmp/build_n5qhc5pi52o4/node_modules/pg/lib/client.js:259:6)
           at Class.Base.extend.runSql (/tmp/build_n5qhc5pi52o4/node_modules/db-migrate/lib/driver/pg.js:194:31)
           at /tmp/build_n5qhc5pi52o4/migrations/20130603050403-initial.js:11:8
           at fs.js:207:20
           at Object.oncomplete (fs.js:107:15)
```

I am getting this error when attempting to use runSql. This only happens for some database URIs for some reason.

The URI looks like this:

```
postgres://user:pass@ec2-107-20-217-22.compute-1.amazonaws.com:5432/d15ersdfkf03bu
```

When running locally instead of on Heroku, I am getting:

```
[ERROR] error: no pg_hba.conf entry for host "244.11.222.111", user "user", database "d15ersdfkf03bu", SSL off
```

**Comment by wzrdtales** [comment]
already implemented
